# Generated by Django 3.0.8 on 2020-07-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OGInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the interface')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description of the interface')),
                ('github_link', models.URLField(verbose_name='Link to GitHub repository of the interface')),
                ('module_name', models.CharField(max_length=50, verbose_name='Name of the python module where a parser class should be stored')),
                ('class_name', models.CharField(max_length=50, verbose_name='Name of a class name for a parser')),
            ],
        ),
        migrations.CreateModel(
            name='UrlHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Url link for parsing')),
            ],
        ),
    ]
