# Generated by Django 3.0.8 on 2020-07-25 16:59

from django.db import migrations, models
from django.core.management import call_command


def forward_func(apps, schema_editor):
    """
    Load deafult parsers
    """
    call_command('loaddata', '../fixtures/parsers.json')


def backward_func(apps, schema_editor):
    """
    There is no backward func at the moment
    """
    print('Backward mock')


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_auto_20200725_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlhistory',
            name='url',
            field=models.URLField(unique=True, verbose_name='Url link for parsing'),
        ),
        migrations.RunPython(forward_func, backward_func)
    ]
